2020-08-19 15:26:06,847 ERROR: Exception on /user/222 [GET] [in c:\users\zyh\pycharmprojects\flask\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\zyh\pycharmprojects\flask\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\zyh\pycharmprojects\flask\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\zyh\pycharmprojects\flask\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\zyh\pycharmprojects\flask\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\zyh\pycharmprojects\flask\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\zyh\pycharmprojects\flask\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\zyh\pycharmprojects\flask\venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\zyh\PycharmProjects\JianBing-Web\application\routes.py", line 117, in user
    return render_template('user.html', user=user, posts=posts.items,
  File "c:\users\zyh\pycharmprojects\flask\venv\lib\site-packages\flask\templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "c:\users\zyh\pycharmprojects\flask\venv\lib\site-packages\jinja2\environment.py", line 930, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "c:\users\zyh\pycharmprojects\flask\venv\lib\site-packages\jinja2\environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "c:\users\zyh\pycharmprojects\flask\venv\lib\site-packages\jinja2\environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "c:\users\zyh\pycharmprojects\flask\venv\lib\site-packages\jinja2\loaders.py", line 127, in load
    code = environment.compile(source, name, filename)
  File "c:\users\zyh\pycharmprojects\flask\venv\lib\site-packages\jinja2\environment.py", line 638, in compile
    self.handle_exception(source=source_hint)
  File "c:\users\zyh\pycharmprojects\flask\venv\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "c:\users\zyh\pycharmprojects\flask\venv\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\zyh\PycharmProjects\JianBing-Web\application\templates\user.html", line 9, in template
    {% if user.about_me %}<p>{{ “ªæ‰ª∞ΩÈ…‹: user.about_me }}</p>{% endif %}
jinja2.exceptions.TemplateSyntaxError: expected token 'end of print statement', got ':'
2020-08-19 15:27:04,630 INFO: Microblog startup [in C:\Users\zyh\PycharmProjects\JianBing-Web\application\__init__.py:64]
2020-08-19 15:33:05,102 INFO: Microblog startup [in C:\Users\zyh\PycharmProjects\JianBing-Web\application\__init__.py:64]
2020-08-19 15:35:58,590 INFO: Microblog startup [in C:\Users\zyh\PycharmProjects\JianBing-Web\application\__init__.py:64]
2020-08-19 15:37:35,419 INFO: Microblog startup [in C:\Users\zyh\PycharmProjects\JianBing-Web\application\__init__.py:64]
2020-08-19 15:38:59,818 INFO: Microblog startup [in C:\Users\zyh\PycharmProjects\JianBing-Web\application\__init__.py:64]
